[project]
name = "monarch-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.32.0",
    "polars-lts-cpu>=1.32.0",
    "python-slugify>=8.0.4",
]

[dependency-groups]
dev = [
    "ruff>=0.12.7",
]
